source "http://rubygems.org"

gem "guard-compass", :git => "git://github.com/welaika/guard-compass.git"
gem "guard-coffeescript"
gem "rb-fsevent"
gem "growl"
gem "guard"
gem "json"
gem "lemonade"
gem "fancy-buttons"